
export const langContent = {
    en: {
        cover_page: {
            title: "Let's create a post",
        },
        navbar: {
            home: 'Home',
            premium: "Premium",
            profile: "Profile",
        },
        postcard: {
            comment: "Comment",
            follow: "Follow",
            unfollow: "Unfollow",
            transfer_points: "Transfer Points",
            description: "Description",
            comment_placeholder: "Write a comment",
            add_comment: "Add comment",
            points: "Points",
            followers: "Followers",
            watching: "Watching",
            points_label: "Points to transfer",
            point_transfer: "Transfer",
            alerts: {
                error_post: "Posts not found",
                post_error: "Something wrong",
                like_success: "Post is liked",
                dislike_success: "Post is disliked",
                comment_error: "There is an error. Can't add comment",
                comment_success: "Comment is added",
                follow_success: "You have followed",
                unfollow_success: "You have unfollowed",
            }
        },
        sign_up: {
            sending: "Sending",
            verifying: "Verifying",
            veriy_emailOtp: "Verify email OTP",
            send_email: "Send email OTP",
            send_phone: "Send phone OTP",
            verify_phone: "Verify phone OTP",
            signup: "SignUp",
            have_account: "Already have an account",
            alerts: {
                send_email: "OTP is sent. Please check your email",
                alert_error: "Something went wrong",
                done_verify: "Verification done!",
                send_phone: "OTP is sent. Please check your message",
                invalid_otp: "OTP is invalid",
                verify_email: "Verify your email address",
                verify_phone: "Verify your phone number",
                register_success: "You are registered successfully",
                tryagain: "Please try again",
            }
        },
        login:{
            email_placeholder:"Enter email",
            phone_placeholder:"Enter phone",
            password_placeholder:"Enter your password",
            enter_otp:"Enter OTP",
            login:"Login",
            donthave:"Don't have an account?",
            alerts:{
                recapcha:"Fill the recapcha",
                login_error:"Please try again",
                login_success:"Login successful",
                mobile_access_time:"You can access this site with mobile between '06:00' to '20:00'",
            }
        },
        subscription:{
            plan:"Select Your Plan",
            heading1:"Basic Plan",
            heading2:"Free Plan",
            rate1:"₹ 100",
            rate2:"₹ 1000",
            month:"/month",
            year:"/year",
            para1:"10 posts per day",
            para2:"Priority support",
            para3:"Access to community",
            active:"Active",
            subs_monthly:"Subscribe monthly",
            subs_yearly:"Subscribe yearly",
            rate3:"₹ 0",
            para4:"1 post per day",
            para5:"2 posts per day when followers are greater than 500",
            para6:"5 posts per day when followers are greater than 1000",
            para7:"Basic support",
            heading3:"Premium Plan",
            rate4:"₹ 500",
            rate5:"₹ 5000",
            para8:"Unlimited posts",
            para9:"Premium support",
            para10:"Access to community",
            alerts:{
                razorpay_fail:"Razorpay SDK failed to load. Are you online?",
                razorpay_error:"Server error. Are you online?",
            }
        },
        profile:{
           not_found:"Posts not found",
           your_profile:"Your Profile",
           nav:{
            home:"Home",
            details:"Details",
            rewards:"Rewards",
            subs:"Subscription",
            langs:"Language",
            posts:"Your posts",
           },
           heading2:"Your Details",
           name:"Name",
           email:"Email",
           phone:"Phone",
           heading3:"Rewards",
           points:"Points",
           followers:"Followers",
           followed:"Followed",
           subs_plan:"Subscription plans",
           free_plan:"Free Plan",
           always_active:"Always Active",
           other_plan:"Other Plans",
           heading4:"Language settings",
           createdAt:"Created At",
           likes:"Likes",
           description:"Description",
           comment:"Comments",
           alerts:{
            comment_delete:"Comment is deleted successfully!",
            delete_error:"Error! Try again.",
            post_delete:"Post has been deleted.",
            update_title:"Title has been updated!",
            update_description:"Description has been updated!",
           }
        },
        createPost:{
            heading1:"Create a new post",
            post_type:"Post Type",
            description:"Description",
            upload:"Upload",
            sending_otp:"Sending OTP",
            sent_otp:"OTP is sent. Check your mail",
            create:"Create Post",
            max_char:"Maximum 75 characters",
            alerts:{
                size_error:"Video size exceeds the maximum limit of",
                duration_error:"Video duration exceeds the maximum limit of",
                otp_problem:"Problem in sending OTP. Try again.",
                otp_invalid:"OTP is invalid. Try again",
                failed:"Failed to create post. Please try again."
            }
        }
    },
    hi: {
        cover_page: {
            title: "आइए एक पोस्ट बनाएं",
        },
        navbar: {
            home: 'होम',
            premium: "प्रीमियम",
            profile: "प्रोफाइल",
        },
        postcard: {
            comment: "टिप्पणी",
            follow: "फॉलो करें",
            unfollow: "अनफॉलो करें",
            transfer_points: "अंक ट्रांसफर करें",
            description: "विवरण",
            comment_placeholder: "टिप्पणी लिखें",
            add_comment: "टिप्पणी जोड़ें",
            points: "अंक",
            followers: "फॉलोअर्स",
            watching: "देख रहे हैं",
            points_label: "ट्रांसफर करने के लिए अंक",
            point_transfer: "ट्रांसफर",
            alerts: {
                error_post: "पोस्ट नहीं मिली",
                post_error: "कुछ गलत हो गया",
                like_success: "पोस्ट को पसंद किया गया",
                dislike_success: "पोस्ट को नापसंद किया गया",
                comment_error: "एक त्रुटि है। टिप्पणी जोड़ नहीं सकते",
                comment_success: "टिप्पणी जोड़ी गई",
                follow_success: "आपने फॉलो किया है",
                unfollow_success: "आपने अनफॉलो किया है",
            }
        },
        sign_up: {
            sending: "भेजा जा रहा है",
            verifying: "सत्यापन हो रहा है",
            veriy_emailOtp: "ईमेल ओटीपी सत्यापित करें",
            send_email: "ईमेल ओटीपी भेजें",
            send_phone: "फोन ओटीपी भेजें",
            verify_phone: "फोन ओटीपी सत्यापित करें",
            signup: "साइन अप करें",
            have_account: "पहले से ही एक खाता है",
            alerts: {
                send_email: "ओटीपी भेजा गया है। कृपया अपना ईमेल देखें",
                alert_error: "कुछ गलत हो गया",
                done_verify: "सत्यापन हो गया!",
                send_phone: "ओटीपी भेजा गया है। कृपया अपना संदेश देखें",
                invalid_otp: "ओटीपी अमान्य है",
                verify_email: "अपना ईमेल पता सत्यापित करें",
                verify_phone: "अपना फोन नंबर सत्यापित करें",
                register_success: "आपने सफलतापूर्वक पंजीकरण किया है",
                tryagain: "कृपया पुन: प्रयास करें",
            }
        },
        login: {
            email_placeholder: "ईमेल दर्ज करें",
            phone_placeholder: "फोन नंबर दर्ज करें",
            password_placeholder: "अपना पासवर्ड दर्ज करें",
            enter_otp: "OTP दर्ज करें",
            login: "लॉगिन",
            donthave: "क्या आपके पास खाता नहीं है?",
            alerts: {
                recapcha: "कैप्चा भरें",
                login_error: "कृपया पुनः प्रयास करें",
                login_success: "लॉगिन सफल",
                mobile_access_time: "आप इस साइट को मोबाइल से '06:00' से '20:00' के बीच एक्सेस कर सकते हैं"
            }
        },
        subscription: {
            plan: "अपनी योजना चुनें",
            heading1: "बेसिक प्लान",
            heading2: "फ्री प्लान",
            rate1: "₹ 100",
            rate2: "₹ 1000",
            month: "/माह",
            year: "/वर्ष",
            para1: "प्रति दिन 10 पोस्ट",
            para2: "प्राथमिकता समर्थन",
            para3: "समुदाय तक पहुँच",
            active: "सक्रिय",
            subs_monthly: "मासिक सदस्यता",
            subs_yearly: "वार्षिक सदस्यता",
            rate3: "₹ 0",
            para4: "प्रति दिन 1 पोस्ट",
            para5: "500 से अधिक अनुयायियों के लिए प्रति दिन 2 पोस्ट",
            para6: "1000 से अधिक अनुयायियों के लिए प्रति दिन 5 पोस्ट",
            para7: "बेसिक समर्थन",
            heading3: "प्रीमियम प्लान",
            rate4: "₹ 500",
            rate5: "₹ 5000",
            para8: "असीमित पोस्ट",
            para9: "प्रीमियम समर्थन",
            para10: "समुदाय तक पहुँच",
            alerts: {
                razorpay_fail: "रज़र्पे SDK लोड करने में विफल। क्या आप ऑनलाइन हैं?",
                razorpay_error: "सर्वर त्रुटि। क्या आप ऑनलाइन हैं?",
            }
        },
        profile: {
            not_found: "पोस्ट नहीं मिली",
            your_profile: "आपकी प्रोफाइल",
            nav: {
                home: "होम",
                details: "विवरण",
                rewards: "पुरस्कार",
                subs: "सदस्यता",
                langs: "भाषा",
                posts: "आपकी पोस्ट्स",
            },
            heading2: "आपके विवरण",
            name: "नाम",
            email: "ईमेल",
            phone: "फोन",
            heading3: "पुरस्कार",
            points: "अंक",
            followers: "अनुयायी",
            followed: "अनुयायियों द्वारा अनुसरण किया गया",
            subs_plan: "सदस्यता योजनाएँ",
            free_plan: "फ्री प्लान",
            always_active: "हमेशा सक्रिय",
            other_plan: "अन्य योजनाएँ",
            heading4: "भाषा सेटिंग्स",
            createdAt: "बनाया गया",
            likes: "लाइक्स",
            description: "विवरण",
            comment: "टिप्पणियाँ",
            alerts: {
                comment_delete: "टिप्पणी सफलतापूर्वक हटाई गई है!",
                delete_error: "त्रुटि! पुन: प्रयास करें।",
                post_delete: "पोस्ट हटा दी गई है।",
                update_title: "शीर्षक अपडेट कर दिया गया है!",
                update_description: "विवरण अपडेट कर दिया गया है!",
            }
        },
        createPost: {
            heading1: "नई पोस्ट बनाएं",
            post_type: "पोस्ट प्रकार",
            description: "विवरण",
            upload: "अपलोड करें",
            sending_otp: "OTP भेज रहा है",
            sent_otp: "OTP भेजा गया है। अपनी मेल जांचें",
            create: "पोस्ट बनाएं",
            max_char: "अधिकतम 75 वर्ण",
            alerts: {
                size_error: "वीडियो का आकार अधिकतम सीमा से अधिक है",
                duration_error: "वीडियो की अवधि अधिकतम सीमा से अधिक है",
                otp_problem: "OTP भेजने में समस्या। पुनः प्रयास करें।",
                otp_invalid: "OTP अमान्य है। पुनः प्रयास करें",
                failed: "पोस्ट बनाने में विफल। कृपया पुन: प्रयास करें।"
            }
        }
    },
    es: {
        cover_page: {
            title: "Vamos a crear una publicación",
        },
        navbar: {
            home: 'Inicio',
            premium: "Premium",
            profile: "Perfil",
        },
        postcard: {
            comment: "Comentario",
            follow: "Seguir",
            unfollow: "Dejar de seguir",
            transfer_points: "Transferir puntos",
            description: "Descripción",
            comment_placeholder: "Escribe un comentario",
            add_comment: "Agregar comentario",
            points: "Puntos",
            followers: "Seguidores",
            watching: "Viendo",
            points_label: "Puntos para transferir",
            point_transfer: "Transferir",
            alerts: {
                error_post: "Publicaciones no encontradas",
                post_error: "Algo salió mal",
                like_success: "Publicación gustada",
                dislike_success: "Publicación no gustada",
                comment_error: "Hay un error. No se puede agregar comentario",
                comment_success: "Comentario agregado",
                follow_success: "Has seguido",
                unfollow_success: "Has dejado de seguir",
            }
        },
        sign_up: {
            sending: "Enviando",
            verifying: "Verificando",
            veriy_emailOtp: "Verificar OTP del correo electrónico",
            send_email: "Enviar OTP por correo electrónico",
            send_phone: "Enviar OTP por teléfono",
            verify_phone: "Verificar OTP por teléfono",
            signup: "Registrarse",
            have_account: "¿Ya tienes una cuenta?",
            alerts: {
                send_email: "OTP enviado. Por favor revisa tu correo electrónico",
                alert_error: "Algo salió mal",
                done_verify: "¡Verificación completa!",
                send_phone: "OTP enviado. Por favor revisa tu mensaje",
                invalid_otp: "OTP no válido",
                verify_email: "Verifica tu dirección de correo electrónico",
                verify_phone: "Verifica tu número de teléfono",
                register_success: "Te has registrado con éxito",
                tryagain: "Por favor, inténtalo de nuevo",
            }
        },
        login: {
            email_placeholder: "Ingrese el correo electrónico",
            phone_placeholder: "Ingrese el teléfono",
            password_placeholder: "Ingrese su contraseña",
            enter_otp: "Ingrese OTP",
            login: "Iniciar sesión",
            donthave: "¿No tienes una cuenta?",
            alerts: {
                recapcha: "Rellena el recapcha",
                login_error: "Por favor, inténtelo de nuevo",
                login_success: "Inicio de sesión exitoso",
                mobile_access_time: "Puede acceder a este sitio con el móvil entre las '06:00' y las '20:00'"
            }
        },
        subscription: {
            plan: "Seleccione su plan",
            heading1: "Plan Básico",
            heading2: "Plan Gratuito",
            rate1: "₹ 100",
            rate2: "₹ 1000",
            month: "/mes",
            year: "/año",
            para1: "10 publicaciones por día",
            para2: "Soporte prioritario",
            para3: "Acceso a la comunidad",
            active: "Activo",
            subs_monthly: "Suscripción mensual",
            subs_yearly: "Suscripción anual",
            rate3: "₹ 0",
            para4: "1 publicación por día",
            para5: "2 publicaciones por día cuando los seguidores son más de 500",
            para6: "5 publicaciones por día cuando los seguidores son más de 1000",
            para7: "Soporte básico",
            heading3: "Plan Premium",
            rate4: "₹ 500",
            rate5: "₹ 5000",
            para8: "Publicaciones ilimitadas",
            para9: "Soporte premium",
            para10: "Acceso a la comunidad",
            alerts: {
                razorpay_fail: "La carga del SDK de Razorpay falló. ¿Estás en línea?",
                razorpay_error: "Error del servidor. ¿Estás en línea?",
            }
        },
        profile: {
            not_found: "No se encontraron publicaciones",
            your_profile: "Tu perfil",
            nav: {
                home: "Inicio",
                details: "Detalles",
                rewards: "Recompensas",
                subs: "Suscripción",
                langs: "Idioma",
                posts: "Tus publicaciones",
            },
            heading2: "Tus detalles",
            name: "Nombre",
            email: "Correo electrónico",
            phone: "Teléfono",
            heading3: "Recompensas",
            points: "Puntos",
            followers: "Seguidores",
            followed: "Seguido",
            subs_plan: "Planes de suscripción",
            free_plan: "Plan Gratuito",
            always_active: "Siempre activo",
            other_plan: "Otros planes",
            heading4: "Configuración del idioma",
            createdAt: "Creado en",
            likes: "Me gusta",
            description: "Descripción",
            comment: "Comentarios",
            alerts: {
                comment_delete: "¡El comentario ha sido eliminado con éxito!",
                delete_error: "¡Error! Inténtalo de nuevo.",
                post_delete: "La publicación ha sido eliminada.",
                update_title: "¡El título ha sido actualizado!",
                update_description: "¡La descripción ha sido actualizada!",
            }
        },
        createPost: {
            heading1: "Crear una nueva publicación",
            post_type: "Tipo de publicación",
            description: "Descripción",
            upload: "Subir",
            sending_otp: "Enviando OTP",
            sent_otp: "OTP enviado. Revisa tu correo",
            create: "Crear publicación",
            max_char: "Máximo 75 caracteres",
            alerts: {
                size_error: "El tamaño del video excede el límite máximo de",
                duration_error: "La duración del video excede el límite máximo de",
                otp_problem: "Problema al enviar OTP. Inténtalo de nuevo.",
                otp_invalid: "OTP no es válido. Inténtalo de nuevo",
                failed: "No se pudo crear la publicación. Por favor intente de nuevo."
            }
        }
    },
    pt: {
        cover_page: {
            title: "Vamos criar uma postagem",
        },
        navbar: {
            home: 'Início',
            premium: "Premium",
            profile: "Perfil",
        },
        postcard: {
            comment: "Comentário",
            follow: "Seguir",
            unfollow: "Deixar de seguir",
            transfer_points: "Transferir pontos",
            description: "Descrição",
            comment_placeholder: "Escreva um comentário",
            add_comment: "Adicionar comentário",
            points: "Pontos",
            followers: "Seguidores",
            watching: "Assistindo",
            points_label: "Pontos para transferir",
            point_transfer: "Transferir",
            alerts: {
                error_post: "Publicações não encontradas",
                post_error: "Algo deu errado",
                like_success: "Publicação curtida",
                dislike_success: "Publicação não curtida",
                comment_error: "Há um erro. Não é possível adicionar comentário",
                comment_success: "Comentário adicionado",
                follow_success: "Você seguiu",
                unfollow_success: "Você deixou de seguir",
            }
        },
        sign_up: {
            sending: "Enviando",
            verifying: "Verificando",
            veriy_emailOtp: "Verificar OTP do e-mail",
            send_email: "Enviar OTP por e-mail",
            send_phone: "Enviar OTP por telefone",
            verify_phone: "Verificar OTP por telefone",
            signup: "Inscrever-se",
            have_account: "Já tem uma conta?",
            alerts: {
                send_email: "OTP enviado. Por favor, verifique seu e-mail",
                alert_error: "Algo deu errado",
                done_verify: "Verificação concluída!",
                send_phone: "OTP enviado. Por favor, verifique sua mensagem",
                invalid_otp: "OTP inválido",
                verify_email: "Verifique seu endereço de e-mail",
                verify_phone: "Verifique seu número de telefone",
                register_success: "Você se registrou com sucesso",
                tryagain: "Por favor, tente novamente",
            }
        },
        login: {
            email_placeholder: "Digite o e-mail",
            phone_placeholder: "Digite o telefone",
            password_placeholder: "Digite sua senha",
            enter_otp: "Digite o OTP",
            login: "Entrar",
            donthave: "Não tem uma conta?",
            alerts: {
                recapcha: "Preencha o recapcha",
                login_error: "Por favor, tente novamente",
                login_success: "Login bem-sucedido",
                mobile_access_time: "Você pode acessar este site com o celular entre '06:00' e '20:00'"
            }
        },
        subscription: {
            plan: "Selecione seu plano",
            heading1: "Plano Básico",
            heading2: "Plano Gratuito",
            rate1: "₹ 100",
            rate2: "₹ 1000",
            month: "/mês",
            year: "/ano",
            para1: "10 postagens por dia",
            para2: "Suporte prioritário",
            para3: "Acesso à comunidade",
            active: "Ativo",
            subs_monthly: "Assinatura mensal",
            subs_yearly: "Assinatura anual",
            rate3: "₹ 0",
            para4: "1 postagem por dia",
            para5: "2 postagens por dia quando os seguidores são mais de 500",
            para6: "5 postagens por dia quando os seguidores são mais de 1000",
            para7: "Suporte básico",
            heading3: "Plano Premium",
            rate4: "₹ 500",
            rate5: "₹ 5000",
            para8: "Postagens ilimitadas",
            para9: "Suporte premium",
            para10: "Acesso à comunidade",
            alerts: {
                razorpay_fail: "Falha ao carregar o SDK do Razorpay. Você está online?",
                razorpay_error: "Erro do servidor. Você está online?",
            }
        },
        profile: {
            not_found: "Postagens não encontradas",
            your_profile: "Seu perfil",
            nav: {
                home: "Início",
                details: "Detalhes",
                rewards: "Recompensas",
                subs: "Assinatura",
                langs: "Idioma",
                posts: "Suas postagens",
            },
            heading2: "Seus detalhes",
            name: "Nome",
            email: "E-mail",
            phone: "Telefone",
            heading3: "Recompensas",
            points: "Pontos",
            followers: "Seguidores",
            followed: "Seguindo",
            subs_plan: "Planos de assinatura",
            free_plan: "Plano Gratuito",
            always_active: "Sempre ativo",
            other_plan: "Outros planos",
            heading4: "Configurações de idioma",
            createdAt: "Criado em",
            likes: "Curtidas",
            description: "Descrição",
            comment: "Comentários",
            alerts: {
                comment_delete: "Comentário foi excluído com sucesso!",
                delete_error: "Erro! Tente novamente.",
                post_delete: "A postagem foi excluída.",
                update_title: "O título foi atualizado!",
                update_description: "A descrição foi atualizada!",
            }
        },
        createPost: {
            heading1: "Criar uma nova postagem",
            post_type: "Tipo de postagem",
            description: "Descrição",
            upload: "Carregar",
            sending_otp: "Enviando OTP",
            sent_otp: "OTP enviado. Verifique seu e-mail",
            create: "Criar postagem",
            max_char: "Máximo 75 caracteres",
            alerts: {
                size_error: "O tamanho do vídeo excede o limite máximo de",
                duration_error: "A duração do vídeo excede o limite máximo de",
                otp_problem: "Problema ao enviar OTP. Tente novamente.",
                otp_invalid: "OTP é inválido. Tente novamente",
                failed: "Falha ao criar a postagem. Por favor, tente novamente."
            }
        }
    },
    ta: {
        cover_page: {
            title: "ஒரு பதிவை உருவாக்கலாம்",
        },
        navbar: {
            home: 'முகப்பு',
            premium: "பிரீமியம்",
            profile: "சுயவிவரம்",
        },
        postcard: {
            comment: "கருத்து",
            follow: "பின்தொடரவும்",
            unfollow: "பின்தொடர்வதை நிறுத்தவும்",
            transfer_points: "புள்ளிகளை மாற்றம் செய்க",
            description: "விளக்கம்",
            comment_placeholder: "கருத்தை எழுதுங்கள்",
            add_comment: "கருத்து சேர்க்க",
            points: "புள்ளிகள்",
            followers: "பின்தொடர்பவர்கள்",
            watching: "பார்க்கின்றனர்",
            points_label: "மாற்றம் செய்ய புள்ளிகள்",
            point_transfer: "மாற்றம் செய்க",
            alerts: {
                error_post: "பதிவுகள் கிடைக்கவில்லை",
                post_error: "ஏதோ தவறாக நடந்து விட்டது",
                like_success: "பதிவு பிடித்தது",
                dislike_success: "பதிவு பிடிக்கவில்லை",
                comment_error: "ஒரு பிழை உள்ளது. கருத்தைச் சேர்க்க முடியவில்லை",
                comment_success: "கருத்து சேர்க்கப்பட்டது",
                follow_success: "நீங்கள் பின்தொடர்கிறீர்கள்",
                unfollow_success: "நீங்கள் பின்தொடர்வதை நிறுத்தியுள்ளீர்கள்",
            }
        },
        sign_up: {
            sending: "அனுப்புகிறது",
            verifying: "சரிபார்க்கிறது",
            veriy_emailOtp: "மின்னஞ்சல் OTP ஐ சரிபார்க்கவும்",
            send_email: "மின்னஞ்சல் OTP ஐ அனுப்பவும்",
            send_phone: "தொலைபேசி OTP ஐ அனுப்பவும்",
            verify_phone: "தொலைபேசி OTP ஐ சரிபார்க்கவும்",
            signup: "பதிவு செய்ய",
            have_account: "ஏற்கனவே ஒரு கணக்கு உள்ளதா",
            alerts: {
                send_email: "OTP அனுப்பப்பட்டது. உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்",
                alert_error: "ஏதோ தவறாக நடந்து விட்டது",
                done_verify: "சரிபார்ப்பு முடிந்தது!",
                send_phone: "OTP அனுப்பப்பட்டது. உங்கள் செய்தியைச் சரிபார்க்கவும்",
                invalid_otp: "OTP தவறானது",
                verify_email: "உங்கள் மின்னஞ்சல் முகவரியை சரிபார்க்கவும்",
                verify_phone: "உங்கள் தொலைபேசி எண்ணைச் சரிபார்க்கவும்",
                register_success: "நீங்கள் வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளீர்கள்",
                tryagain: "தயவுசெய்து மீண்டும் முயற்சிக்கவும்",
            }
        },
        login: {
            email_placeholder: "மின்னஞ்சலை உள்ளிடவும்",
            phone_placeholder: "தொலைபேசி எண்ணை உள்ளிடவும்",
            password_placeholder: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
            enter_otp: "OTP-ஐ உள்ளிடவும்",
            login: "உள்நுழைய",
            donthave: "கணக்கு இல்லையா?",
            alerts: {
                recapcha: "ரீகேப்சாவை நிரப்பவும்",
                login_error: "தயவுசெய்து மீண்டும் முயற்சிக்கவும்",
                login_success: "உள்நுழைவு வெற்றி",
                mobile_access_time: "நீங்கள் இந்த தளத்தை '06:00' முதல் '20:00' வரை மொபைல் மூலம் அணுகலாம்"
            }
        },
        subscription: {
            plan: "உங்கள் திட்டத்தைத் தேர்ந்தெடுக்கவும்",
            heading1: "அடிப்படை திட்டம்",
            heading2: "இலவச திட்டம்",
            rate1: "₹ 100",
            rate2: "₹ 1000",
            month: "/மாதம்",
            year: "/ஆண்டு",
            para1: "ஒரு நாளைக்கு 10 பதிவுகள்",
            para2: "முன்னுரிமை ஆதரவு",
            para3: "சமூகத்தில் அணுகல்",
            active: "செயலில்",
            subs_monthly: "மாதாந்திர சந்தா",
            subs_yearly: "வருடாந்திர சந்தா",
            rate3: "₹ 0",
            para4: "ஒரு நாளைக்கு 1 பதிவு",
            para5: "பின்தொடர்பவர்கள் 500 இற்கு மேல் இருந்தால் ஒரு நாளுக்கு 2 பதிவுகள்",
            para6: "பின்தொடர்பவர்கள் 1000 இற்கு மேல் இருந்தால் ஒரு நாளுக்கு 5 பதிவுகள்",
            para7: "அடிப்படை ஆதரவு",
            heading3: "பிரீமியம் திட்டம்",
            rate4: "₹ 500",
            rate5: "₹ 5000",
            para8: "முடியாத பதிவுகள்",
            para9: "பிரீமியம் ஆதரவு",
            para10: "சமூகத்தில் அணுகல்",
            alerts: {
                razorpay_fail: "ரேசர்பே SDK ஏற்றத்தில் தோல்வி. நீங்கள் ஆன்லைனில் உள்ளீர்களா?",
                razorpay_error: "சர்வர் பிழை. நீங்கள் ஆன்லைனில் உள்ளீர்களா?",
            }
        },
        profile: {
            not_found: "பதிவுகள் இல்லை",
            your_profile: "உங்கள் சுயவிவரம்",
            nav: {
                home: "முகப்பு",
                details: "விவரங்கள்",
                rewards: "வெகுமதிகள்",
                subs: "சந்தா",
                langs: "மொழி",
                posts: "உங்கள் பதிவுகள்",
            },
            heading2: "உங்கள் விவரங்கள்",
            name: "பெயர்",
            email: "மின்னஞ்சல்",
            phone: "தொலைபேசி",
            heading3: "வெகுமதிகள்",
            points: "புள்ளிகள்",
            followers: "பின்தொடர்பவர்கள்",
            followed: "பின்தொடரப்பட்டது",
            subs_plan: "சந்தா திட்டங்கள்",
            free_plan: "இலவச திட்டம்",
            always_active: "எப்போதும் செயலில்",
            other_plan: "மற்ற திட்டங்கள்",
            heading4: "மொழி அமைப்புகள்",
            createdAt: "உருவாக்கப்பட்டது",
            likes: "விருப்பங்கள்",
            description: "விவரம்",
            comment: "கருத்துக்கள்",
            alerts: {
                comment_delete: "கருத்து வெற்றிகரமாக நீக்கப்பட்டது!",
                delete_error: "பிழை! மீண்டும் முயற்சிக்கவும்.",
                post_delete: "பதிவு நீக்கப்பட்டது.",
                update_title: "தலைப்பு புதுப்பிக்கப்பட்டது!",
                update_description: "விளக்கம் புதுப்பிக்கப்பட்டது!",
            }
        },
        createPost: {
            heading1: "ஒரு புதிய பதிவை உருவாக்கவும்",
            post_type: "பதிவு வகை",
            description: "விளக்கம்",
            upload: "பதிவேற்றம்",
            sending_otp: "OTP அனுப்புகிறது",
            sent_otp: "OTP அனுப்பப்பட்டது. உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்",
            create: "பதிவை உருவாக்கவும்",
            max_char: "அதிகபட்சம் 75 எழுத்துகள்",
            alerts: {
                size_error: "வீடியோ அளவு அதிகபட்ச எல்லையை மீறுகிறது",
                duration_error: "வீடியோ காலம் அதிகபட்ச எல்லையை மீறுகிறது",
                otp_problem: "OTP அனுப்புவதில் சிக்கல். மீண்டும் முயற்சிக்கவும்.",
                otp_invalid: "OTP தவறானது. மீண்டும் முயற்சிக்கவும்",
                failed: "பதிவை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்."
            }
        }
    },
    bn: {
        cover_page: {
            title: "আসুন একটি পোস্ট তৈরি করি",
        },
        navbar: {
            home: 'হোম',
            premium: "প্রিমিয়াম",
            profile: "প্রোফাইল",
        },
        postcard: {
            comment: "মন্তব্য",
            follow: "অনুসরণ করুন",
            unfollow: "অনুসরণ বন্ধ করুন",
            transfer_points: "পয়েন্ট স্থানান্তর",
            description: "বর্ণনা",
            comment_placeholder: "একটি মন্তব্য লিখুন",
            add_comment: "মন্তব্য যোগ করুন",
            points: "পয়েন্ট",
            followers: "অনুসরণকারীরা",
            watching: "দেখছেন",
            points_label: "স্থানান্তর করতে পয়েন্ট",
            point_transfer: "স্থানান্তর",
            alerts: {
                error_post: "পোস্ট পাওয়া যায়নি",
                post_error: "কিছু ভুল হয়েছে",
                like_success: "পোস্ট পছন্দ হয়েছে",
                dislike_success: "পোস্ট অপছন্দ হয়েছে",
                comment_error: "একটি ত্রুটি রয়েছে। মন্তব্য যোগ করা যাবে না",
                comment_success: "মন্তব্য যোগ করা হয়েছে",
                follow_success: "আপনি অনুসরণ করেছেন",
                unfollow_success: "আপনি অনুসরণ বন্ধ করেছেন",
            }
        },
        sign_up: {
            sending: "প্রেরণ করা হচ্ছে",
            verifying: "যাচাই করা হচ্ছে",
            veriy_emailOtp: "ইমেল OTP যাচাই করুন",
            send_email: "ইমেল OTP পাঠান",
            send_phone: "ফোন OTP পাঠান",
            verify_phone: "ফোন OTP যাচাই করুন",
            signup: "সাইন আপ করুন",
            have_account: "আগেই একটি অ্যাকাউন্ট আছে",
            alerts: {
                send_email: "OTP পাঠানো হয়েছে। আপনার ইমেল চেক করুন",
                alert_error: "কিছু ভুল হয়েছে",
                done_verify: "যাচাই সম্পন্ন!",
                send_phone: "OTP পাঠানো হয়েছে। আপনার বার্তা চেক করুন",
                invalid_otp: "OTP অবৈধ",
                verify_email: "আপনার ইমেল ঠিকানা যাচাই করুন",
                verify_phone: "আপনার ফোন নম্বর যাচাই করুন",
                register_success: "আপনি সফলভাবে নিবন্ধিত হয়েছেন",
                tryagain: "আবার চেষ্টা করুন",
            }
        },
        login: {
            email_placeholder: "ইমেইল লিখুন",
            phone_placeholder: "ফোন নম্বর লিখুন",
            password_placeholder: "আপনার পাসওয়ার্ড লিখুন",
            enter_otp: "OTP লিখুন",
            login: "লগইন",
            donthave: "অ্যাকাউন্ট নেই?",
            alerts: {
                recapcha: "রিক্যাপচা পূরণ করুন",
                login_error: "অনুগ্রহ করে আবার চেষ্টা করুন",
                login_success: "লগইন সফল",
                mobile_access_time: "আপনি মোবাইল দিয়ে এই সাইটটি '06:00' থেকে '20:00' এর মধ্যে অ্যাক্সেস করতে পারেন"
            }
        },
        subscription: {
            plan: "আপনার পরিকল্পনা নির্বাচন করুন",
            heading1: "বেসিক প্ল্যান",
            heading2: "ফ্রি প্ল্যান",
            rate1: "₹ 100",
            rate2: "₹ 1000",
            month: "/মাস",
            year: "/বছর",
            para1: "প্রতি দিন 10 পোস্ট",
            para2: "অগ্রাধিকার সহায়তা",
            para3: "সম্প্রদায়ের প্রবেশাধিকার",
            active: "সক্রিয়",
            subs_monthly: "মাসিক সাবস্ক্রিপশন",
            subs_yearly: "বার্ষিক সাবস্ক্রিপশন",
            rate3: "₹ 0",
            para4: "প্রতি দিন 1 পোস্ট",
            para5: "অনুসারীরা 500 এর বেশি হলে প্রতি দিন 2 পোস্ট",
            para6: "অনুসারীরা 1000 এর বেশি হলে প্রতি দিন 5 পোস্ট",
            para7: "বেসিক সহায়তা",
            heading3: "প্রিমিয়াম প্ল্যান",
            rate4: "₹ 500",
            rate5: "₹ 5000",
            para8: "সীমাহীন পোস্ট",
            para9: "প্রিমিয়াম সহায়তা",
            para10: "সম্প্রদায়ের প্রবেশাধিকার",
            alerts: {
                razorpay_fail: "রেজারপে SDK লোড করতে ব্যর্থ হয়েছে। আপনি অনলাইনে আছেন?",
                razorpay_error: "সার্ভার ত্রুটি। আপনি অনলাইনে আছেন?",
            }
        },
        profile: {
            not_found: "পোস্ট পাওয়া যায়নি",
            your_profile: "আপনার প্রোফাইল",
            nav: {
                home: "হোম",
                details: "বিস্তারিত",
                rewards: "পুরস্কার",
                subs: "সাবস্ক্রিপশন",
                langs: "ভাষা",
                posts: "আপনার পোস্টগুলি",
            },
            heading2: "আপনার বিবরণ",
            name: "নাম",
            email: "ইমেইল",
            phone: "ফোন",
            heading3: "পুরস্কার",
            points: "পয়েন্ট",
            followers: "অনুসারীরা",
            followed: "অনুসৃত",
            subs_plan: "সাবস্ক্রিপশন পরিকল্পনা",
            free_plan: "ফ্রি প্ল্যান",
            always_active: "সবসময় সক্রিয়",
            other_plan: "অন্যান্য পরিকল্পনা",
            heading4: "ভাষা সেটিংস",
            createdAt: "তৈরি হয়েছে",
            likes: "লাইক",
            description: "বর্ণনা",
            comment: "মন্তব্য",
            alerts: {
                comment_delete: "মন্তব্য সফলভাবে মুছে ফেলা হয়েছে!",
                delete_error: "ত্রুটি! আবার চেষ্টা করুন।",
                post_delete: "পোস্টটি মুছে ফেলা হয়েছে।",
                update_title: "শিরোনাম আপডেট করা হয়েছে!",
                update_description: "বর্ণনা আপডেট করা হয়েছে!",
            }
        },
        createPost: {
            heading1: "একটি নতুন পোস্ট তৈরি করুন",
            post_type: "পোস্ট টাইপ",
            description: "বর্ণনা",
            upload: "আপলোড করুন",
            sending_otp: "OTP পাঠানো হচ্ছে",
            sent_otp: "OTP পাঠানো হয়েছে। আপনার মেল চেক করুন",
            create: "পোস্ট তৈরি করুন",
            max_char: "সর্বাধিক 75 অক্ষর",
            alerts: {
                size_error: "ভিডিওর আকার সর্বাধিক সীমা অতিক্রম করেছে",
                duration_error: "ভিডিওর সময়কাল সর্বাধিক সীমা অতিক্রম করেছে",
                otp_problem: "OTP পাঠাতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
                otp_invalid: "OTP অবৈধ। আবার চেষ্টা করুন",
                failed: "পোস্ট তৈরি করতে ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।"
            }
        }
    },
    fr: {
        cover_page: {
            title: "Créons une publication",
        },
        navbar: {
            home: 'Accueil',
            premium: "Premium",
            profile: "Profil",
        },
        postcard: {
            comment: "Commentaire",
            follow: "Suivre",
            unfollow: "Ne plus suivre",
            transfer_points: "Transférer des points",
            description: "Description",
            comment_placeholder: "Écrire un commentaire",
            add_comment: "Ajouter un commentaire",
            points: "Points",
            followers: "Abonnés",
            watching: "Regarder",
            points_label: "Points à transférer",
            point_transfer: "Transférer",
            alerts: {
                error_post: "Publications non trouvées",
                post_error: "Quelque chose a mal tourné",
                like_success: "Publication aimée",
                dislike_success: "Publication non aimée",
                comment_error: "Il y a une erreur. Impossible d'ajouter un commentaire",
                comment_success: "Commentaire ajouté",
                follow_success: "Vous avez suivi",
                unfollow_success: "Vous avez arrêté de suivre",
            }
        },
        sign_up: {
            sending: "Envoi",
            verifying: "Vérification",
            veriy_emailOtp: "Vérifier l'OTP de l'email",
            send_email: "Envoyer l'OTP par email",
            send_phone: "Envoyer l'OTP par téléphone",
            verify_phone: "Vérifier l'OTP par téléphone",
            signup: "S'inscrire",
            have_account: "Vous avez déjà un compte",
            alerts: {
                send_email: "OTP envoyé. Veuillez vérifier votre email",
                alert_error: "Quelque chose a mal tourné",
                done_verify: "Vérification terminée!",
                send_phone: "OTP envoyé. Veuillez vérifier votre message",
                invalid_otp: "OTP invalide",
                verify_email: "Vérifiez votre adresse email",
                verify_phone: "Vérifiez votre numéro de téléphone",
                register_success: "Vous vous êtes inscrit avec succès",
                tryagain: "Veuillez réessayer",
            }
        },
        login: {
            email_placeholder: "Entrez l'e-mail",
            phone_placeholder: "Entrez le téléphone",
            password_placeholder: "Entrez votre mot de passe",
            enter_otp: "Entrez le OTP",
            login: "Connexion",
            donthave: "Vous n'avez pas de compte?",
            alerts: {
                recapcha: "Remplissez le recapcha",
                login_error: "Veuillez réessayer",
                login_success: "Connexion réussie",
                mobile_access_time: "Vous pouvez accéder à ce site avec un mobile entre '06:00' et '20:00'"
            }
        },
        subscription: {
            plan: "Sélectionnez votre plan",
            heading1: "Plan de base",
            heading2: "Plan gratuit",
            rate1: "₹ 100",
            rate2: "₹ 1000",
            month: "/mois",
            year: "/an",
            para1: "10 publications par jour",
            para2: "Support prioritaire",
            para3: "Accès à la communauté",
            active: "Actif",
            subs_monthly: "Abonnement mensuel",
            subs_yearly: "Abonnement annuel",
            rate3: "₹ 0",
            para4: "1 publication par jour",
            para5: "2 publications par jour lorsque les abonnés sont supérieurs à 500",
            para6: "5 publications par jour lorsque les abonnés sont supérieurs à 1000",
            para7: "Support de base",
            heading3: "Plan Premium",
            rate4: "₹ 500",
            rate5: "₹ 5000",
            para8: "Publications illimitées",
            para9: "Support premium",
            para10: "Accès à la communauté",
            alerts: {
                razorpay_fail: "Échec du chargement du SDK Razorpay. Êtes-vous en ligne?",
                razorpay_error: "Erreur du serveur. Êtes-vous en ligne?",
            }
        },
        profile: {
            not_found: "Publications non trouvées",
            your_profile: "Votre profil",
            nav: {
                home: "Accueil",
                details: "Détails",
                rewards: "Récompenses",
                subs: "Abonnement",
                langs: "Langue",
                posts: "Vos publications",
            },
            heading2: "Vos détails",
            name: "Nom",
            email: "E-mail",
            phone: "Téléphone",
            heading3: "Récompenses",
            points: "Points",
            followers: "Abonnés",
            followed: "Suivi",
            subs_plan: "Plans d'abonnement",
            free_plan: "Plan gratuit",
            always_active: "Toujours actif",
            other_plan: "Autres plans",
            heading4: "Paramètres de langue",
            createdAt: "Créé à",
            likes: "J'aime",
            description: "Description",
            comment: "Commentaires",
            alerts: {
                comment_delete: "Le commentaire a été supprimé avec succès !",
                delete_error: "Erreur ! Réessayez.",
                post_delete: "Le post a été supprimé.",
                update_title: "Le titre a été mis à jour !",
                update_description: "La description a été mise à jour !",
            }
        },
        createPost: {
            heading1: "Créer un nouveau post",
            post_type: "Type de post",
            description: "Description",
            upload: "Télécharger",
            sending_otp: "Envoi de l'OTP",
            sent_otp: "OTP envoyé. Vérifiez votre mail",
            create: "Créer un post",
            max_char: "Maximum 75 caractères",
            alerts: {
                size_error: "La taille de la vidéo dépasse la limite maximale de",
                duration_error: "La durée de la vidéo dépasse la limite maximale de",
                otp_problem: "Problème lors de l'envoi de l'OTP. Réessayez.",
                otp_invalid: "L'OTP est invalide. Réessayez",
                failed: "Échec de la création du post. Veuillez réessayer."
            }
        }
    }
}

